// 가게 데이터를 중앙에서 관리
export const storesData = {
  1: {
    id: 1,
    name: "맛있는 김치찌개",
    category: "한식",
    discount: 30,
    originalPrice: 12000,
    discountPrice: 8400,
    distance: 0.2,
    timeLeft: "2시간 15분",
    address: "서울시 강남구 역삼동 123-45",
    phone: "02-1234-5678",
    description:
      "정통 한식의 맛을 자랑하는 김치찌개 전문점입니다. 신선한 재료로 매일 끓여내는 진짜 김치찌개를 맛보세요!",
    thumbnail: "/images/kimchi-jjigae-thumb.jpg",
    images: ["/images/kimchi-jjigae-1.jpg", "/images/kimchi-jjigae-2.jpg", "/images/kimchi-jjigae-3.jpg"],
    menu: [
      {
        id: 1,
        name: "김치찌개",
        originalPrice: 12000,
        discountPrice: 8400,
        description: "신김치로 끓인 진짜 김치찌개",
      },
      {
        id: 2,
        name: "된장찌개",
        originalPrice: 11000,
        discountPrice: 7700,
        description: "집된장으로 끓인 구수한 된장찌개",
      },
      {
        id: 3,
        name: "순두부찌개",
        originalPrice: 10000,
        discountPrice: 7000,
        description: "부드러운 순두부가 들어간 얼큰한 찌개",
      },
      { id: 4, name: "공기밥", originalPrice: 2000, discountPrice: 1400, description: "갓 지은 따뜻한 밥" },
      { id: 5, name: "계란말이", originalPrice: 8000, discountPrice: 5600, description: "부드럽고 달콤한 계란말이" },
    ],
  },
  2: {
    id: 2,
    name: "카페 브루잉",
    category: "카페",
    discount: 25,
    originalPrice: 5000,
    discountPrice: 3750,
    distance: 0.1,
    timeLeft: "1시간 30분",
    address: "서울시 강남구 역삼동 456-78",
    phone: "02-2345-6789",
    description: "신선한 원두로 내린 진짜 커피를 맛보세요. 디저트도 직접 만들어 더욱 맛있어요!",
    thumbnail: "/images/cafe-brewing-thumb.jpg",
    images: ["/images/cafe-brewing-1.jpg", "/images/cafe-brewing-2.jpg", "/images/cafe-brewing-3.jpg"],
    menu: [
      { id: 1, name: "아메리카노", originalPrice: 4500, discountPrice: 3375, description: "깔끔하고 진한 아메리카노" },
      {
        id: 2,
        name: "카페라떼",
        originalPrice: 5500,
        discountPrice: 4125,
        description: "부드러운 우유와 에스프레소의 조화",
      },
      {
        id: 3,
        name: "카푸치노",
        originalPrice: 5500,
        discountPrice: 4125,
        description: "풍성한 거품이 일품인 카푸치노",
      },
      { id: 4, name: "크로와상", originalPrice: 3500, discountPrice: 2625, description: "바삭한 프랑스식 크로와상" },
      {
        id: 5,
        name: "치즈케이크",
        originalPrice: 6000,
        discountPrice: 4500,
        description: "진짜 크림치즈로 만든 케이크",
      },
    ],
  },
  3: {
    id: 3,
    name: "헤어살롱 뷰티",
    category: "뷰티",
    discount: 40,
    originalPrice: 25000,
    discountPrice: 15000,
    distance: 0.3,
    timeLeft: "3시간 45분",
    address: "서울시 강남구 역삼동 789-01",
    phone: "02-3456-7890",
    description: "전문 스타일리스트가 고객 한 분 한 분께 맞는 스타일을 제안해드립니다.",
    thumbnail: "/images/hair-salon-thumb.jpg",
    images: ["/images/hair-salon-1.jpg", "/images/hair-salon-2.jpg", "/images/hair-salon-3.jpg"],
    menu: [
      { id: 1, name: "커트", originalPrice: 25000, discountPrice: 15000, description: "기본 헤어 커트" },
      { id: 2, name: "펌", originalPrice: 80000, discountPrice: 48000, description: "자연스러운 웨이브 펌" },
      { id: 3, name: "염색", originalPrice: 60000, discountPrice: 36000, description: "트렌디한 컬러 염색" },
      { id: 4, name: "트리트먼트", originalPrice: 30000, discountPrice: 18000, description: "모발 영양 트리트먼트" },
    ],
  },
  4: {
    id: 4,
    name: "피자마루",
    category: "양식",
    discount: 35,
    originalPrice: 18000,
    discountPrice: 11700,
    distance: 0.4,
    timeLeft: "4시간 20분",
    address: "서울시 강남구 역삼동 234-56",
    phone: "02-4567-8901",
    description: "이탈리아 정통 방식으로 만든 수제 피자를 맛보세요. 신선한 재료만 사용합니다!",
    thumbnail: "/images/pizza-maru-thumb.jpg",
    images: ["/images/pizza-maru-1.jpg", "/images/pizza-maru-2.jpg", "/images/pizza-maru-3.jpg"],
    menu: [
      {
        id: 1,
        name: "마르게리타",
        originalPrice: 18000,
        discountPrice: 11700,
        description: "클래식 토마토 베이스 피자",
      },
      { id: 2, name: "페퍼로니", originalPrice: 20000, discountPrice: 13000, description: "매콤한 페퍼로니 피자" },
      {
        id: 3,
        name: "하와이안",
        originalPrice: 22000,
        discountPrice: 14300,
        description: "파인애플과 햄이 들어간 피자",
      },
      { id: 4, name: "시저샐러드", originalPrice: 8000, discountPrice: 5200, description: "신선한 로메인 샐러드" },
    ],
  },
  5: {
    id: 5,
    name: "스시 오마카세",
    category: "일식",
    discount: 20,
    originalPrice: 35000,
    discountPrice: 28000,
    distance: 0.6,
    timeLeft: "1시간 45분",
    address: "서울시 강남구 역삼동 345-67",
    phone: "02-5678-9012",
    description: "신선한 생선으로 만든 정통 일식 스시를 경험해보세요. 셰프의 정성이 담긴 오마카세!",
    thumbnail: "/images/sushi-omakase-thumb.jpg",
    images: ["/images/sushi-omakase-1.jpg", "/images/sushi-omakase-2.jpg", "/images/sushi-omakase-3.jpg"],
    menu: [
      { id: 1, name: "오마카세 A", originalPrice: 35000, discountPrice: 28000, description: "셰프 추천 스시 10피스" },
      { id: 2, name: "오마카세 B", originalPrice: 50000, discountPrice: 40000, description: "프리미엄 스시 15피스" },
      { id: 3, name: "연어덮밥", originalPrice: 15000, discountPrice: 12000, description: "신선한 연어 사시미 덮밥" },
      { id: 4, name: "미소시루", originalPrice: 3000, discountPrice: 2400, description: "따뜻한 된장국" },
    ],
  },
  6: {
    id: 6,
    name: "네일아트 살롱",
    category: "뷰티",
    discount: 50,
    originalPrice: 30000,
    discountPrice: 15000,
    distance: 0.8,
    timeLeft: "5시간 30분",
    address: "서울시 강남구 역삼동 456-78",
    phone: "02-6789-0123",
    description: "트렌디한 네일아트와 케어를 한번에! 깔끔하고 세련된 디자인을 만나보세요.",
    thumbnail: "/images/nail-salon-thumb.jpg",
    images: ["/images/nail-salon-1.jpg", "/images/nail-salon-2.jpg", "/images/nail-salon-3.jpg"],
    menu: [
      { id: 1, name: "젤네일", originalPrice: 30000, discountPrice: 15000, description: "기본 젤네일 시술" },
      { id: 2, name: "아트네일", originalPrice: 45000, discountPrice: 22500, description: "디자인 아트네일" },
      { id: 3, name: "페디큐어", originalPrice: 25000, discountPrice: 12500, description: "발톱 관리 및 네일" },
      { id: 4, name: "네일케어", originalPrice: 15000, discountPrice: 7500, description: "기본 네일 케어" },
    ],
  },
  7: {
    id: 7,
    name: "중화루",
    category: "중식",
    discount: 25,
    originalPrice: 15000,
    discountPrice: 11250,
    distance: 0.5,
    timeLeft: "3시간 10분",
    address: "서울시 강남구 역삼동 567-89",
    phone: "02-7890-1234",
    description: "정통 중화요리를 맛볼 수 있는 곳입니다. 신선한 재료로 만든 진짜 중국 맛!",
    thumbnail: "/images/chinese-restaurant-thumb.jpg",
    images: ["/images/chinese-1.jpg", "/images/chinese-2.jpg", "/images/chinese-3.jpg"],
    menu: [
      { id: 1, name: "짜장면", originalPrice: 8000, discountPrice: 6000, description: "정통 춘장으로 만든 짜장면" },
      { id: 2, name: "짬뽕", originalPrice: 9000, discountPrice: 6750, description: "얼큰한 해물 짬뽕" },
      { id: 3, name: "탕수육", originalPrice: 15000, discountPrice: 11250, description: "바삭한 탕수육" },
      { id: 4, name: "볶음밥", originalPrice: 8000, discountPrice: 6000, description: "고소한 볶음밥" },
    ],
  },
}

export function getStoreById(id: number) {
  return storesData[id as keyof typeof storesData] || null
}
